### ISSUE TITLE
homebrew install

### ISSUE THREAD

**Issue by Psidium** [kyleneideck/BackgroundMusic#12]
Hello!
First of all: **THANKS**, this is a wonderful tool and I'll be using this forever!

To make it easy to install, do you plan to integrate with `homebrew`? Or maybe `brew cask`?

Would you accept a pull request implementing brew integration? (not that I know exactly how to do it lol)

Cheers

**Comment by adidalal** [comment]
(Homebrew Cask maintainer here)

A `.dmg` with the `.app` bundle/binaries inside, uploaded via Github Releases is probably the most efficient way to get BackgroundMusic in the HBC repo - there's plenty of Casks to model off of, and there is excellent documentation to write your own (but I'm biased 😁)

**Comment by wildeyes** [comment]
@adidalal Could you give an example to a cask I can model?

**Comment by adidalal** [comment]
Just checked out the readme, if there isn't a compiled app it won't work. Unlike Homebrew, HBC is a distribution/packaging tool, not a build tool.

There's a few model Casks in our documentation (see Contributing)

**Comment by ylluminate** [comment]
Anything happen with this? Would sure be handy.

**Comment by sscotth** [comment]
> No binaries yet (working on it)

https://github.com/kyleneideck/BackgroundMusic/blob/f5628e78a9586e9b3b549271ec462efdbd198d97/README.md#install

**Comment by ylluminate** [comment]
Good catch @sscotth. Was asking about this because sadly I hit an odd wall... Xcode is installed properly and working for me, but I'm getting a message about it not being there. After futzing around with that for awhile with no luck, I gave up for the time being.  Will definitely be nice to have binaries. 

I poked about some more where I learned about this app and actually saw an app called Sound Control that just about blew my socks off. Really like the additional functionality of that tool.

At any rate, yes, good to know that we'll have this soon via Homebrew, knock on wood!

**Comment by sscotth** [comment]
I started an unofficial release path using the travis builds, which was successful. However, the `Background Music.app` that Travis creates is currently crashing immediately after opening.

I guess the Travis build script needs work.

https://github.com/sscotth/BackgroundMusic

**Comment by kyleneideck** [comment]
>I poked about some more where I learned about this app and actually saw an app called Sound Control that just about blew my socks off.

I've added it to the links in the README. Thanks.

@sscotth The `Background Music.app` from your fork crashed at launch for me as well. I had run it in a VM without BGMDriver installed and there was a bug where BGMApp would try to continue launching anyway. I've fixed that in 612e249 and now BGMApp quits after showing the error message.

After that, I installed BGMDriver and your `Background Music.app` seemed to work fine. I didn't have BGMXPCHelper installed either, but BGMApp showed the error message about that correctly and after I dismissed it BGMApp launched normally.

Ideally, BGMApp would offer to install BGMDriver and BGMXPCHelper if they're missing (or update them if they're old), but IIRC that would take a fair amount of effort. BGMApp would have to include a separate installer in its bundle and launch it if BGMDriver or BGMXPCHelper are missing. The installer would also have to request elevated permissions first, which seemed a bit complicated from the documentation I read a while ago. 

I think it might be better to start by just putting BGMDriver and BGMXPCHelper in the .zip/.dmg as well, and then work on making installation more user friendly later. I'm not sure how much that would complicate your Homebrew formula, though. Another option would be to make a .pkg installer, which Homebrew Cask also supports.

For reference, the installation process is basically:

 - Copy
    - `Background Music.app` to `/Applications`,
    - `Background Music Device.driver` to `/Library/Audio/Plug-Ins/HAL`, and
    - `BGMXPCHelper.xpc` to `/usr/local/libexec` (or, if its permissions aren't safe, to `/Library/Application Support/Background Music` -- see [safe_install_dir.sh](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMXPCHelper/safe_install_dir.sh)).
 - Run BGMXPCHelper's [post_install.sh](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMXPCHelper/post_install.sh), which
    - creates a user and group for BGMXPCHelper,
    - processes the template for `com.bearisdriving.BGM.XPCHelper.plist`, copies it to `/Library/LaunchDaemons` and registers it with launchd.
 - Restart CoreAudio with `sudo launchctl kill -15 system/com.apple.audio.coreaudiod`.
 - Launch `/Applications/Background Music.app`.

**Comment by kyleneideck** [comment]
>Would you accept a pull request implementing brew integration?

Sorry, @Psidium, I must have missed this question the first time I read this issue. A PR for Homebrew support would be great. I was planning to work on it myself at some point, if someone else didn't do it first, but hadn't gotten around to it.

**Comment by sscotth** [comment]
We could make the BGMDriver and BGMXPCHelper casks of their own and add them in `depends_on`

**Comment by adidalal** [comment]
You don't necessarily need to make them separate Casks - if you can script the process, see https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md

**Comment by dnicolson** [comment]
The [current version](https://github.com/Homebrew/homebrew-cask/commit/f6365a04320b8c7ec1ab42a296b50fc6fddf9b07) of the cask doesn't install properly. Opening the app results in a dialog that the plugin cannot be found but it exists. It suggests running `sudo killall coreaudiod` but that does not resolve the issue. Running the installer afterwards correctly installs the app.

**Comment by ylluminate** [comment]
@yllumarious since we've moved to MacPorts you might be interested in this.

**Comment by ylluminate** [comment]
@ylluminarious since we've moved to MacPorts you might be interested in this.

**Comment by ylluminarious** [comment]
@ylluminate Hmm, it might be easy enough to install in MacPorts, as I see a `build_and_install.sh` script. But I'm not sure how easily it could be uninstalled. MacPorts usually uninstalls things itself by tracking every file which gets installed during installation, [in a process called `destroot`.](https://guide.macports.org/chunked/reference.phases.html#reference.phases.introduction) I'm not sure how easily that would fit with something like this which has to do some complicated steps to perform a complete uninstall. I'm sure it's doable, but I doubt I can work on this soon.

**Comment by JTEgan** [comment]
@kyleneideck  can't this be marked closed, now? Homebrew install is described in the readme, and I've used it successfully.
